# Generated by Django 6.0.1 on 2026-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('technician', 'Technician'), ('customer', 'Customer'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
