# Generated by Django 6.0.1 on 2026-09-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive')], default='corrective', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('repaired', 'Repaired'), ('scrap', 'Scrap'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
