# Generated by Django 6.0.1 on 2026-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerequest_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='duration_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
